### ISSUE TITLE
Inverted terrain features

### ISSUE THREAD

**Issue by JakBBB** [eric-guerin/terrain-amplification#1]
I found some artifacts when synthesizing terrains that show that the example terrain patches are sometimes inverted as shown here https://i.imgur.com/t3gnkI0.jpg

I don't know if this is on purpose and if it is is there a way to turn it off?

**Comment by eric-guerin** [comment]
Terrain patches are combined with a factor that can be negative, so this is always a possibility that the patch is "upside down". This should be possible to change that, as can be seen in this article : 
Oscar Argudo, Carlos Andújar, Antonio Chica, Eric Guérin, Julie Digne, Adrien Peytavie, Eric Galin:
Coherent multi-layer landscape synthesis. The Visual Computer 33(6-8): 1005-1015 (2017)
